import { formatDate } from '../utils/helpers';

export const generatePDFContent = (user, quizConfig, results, questions) => {
  return `
QUIZ RESULTS
================

Student: ${user.name}
Topic: ${quizConfig.topic}
Difficulty: ${quizConfig.difficulty}
Date: ${formatDate(new Date())}

SCORE
-----
${results.score}/${results.total} (${results.percentage}%)

DETAILED RESULTS
----------------
${results.details.map((r, i) => `
Question ${i + 1}: ${r.question}
Your Answer: ${questions[i].options[r.userAnswer] || 'Not answered'}
Correct Answer: ${questions[i].options[r.correctAnswer]}
Status: ${r.isCorrect ? '✓ Correct' : '✗ Incorrect'}
Subtopic: ${r.subtopic}
Explanation: ${r.explanation}
`).join('\n')}

AI FEEDBACK
-----------
${results.feedback}

Generated by AI Quiz Application
`;
};

export const downloadPDF = (content, filename) => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};
